### ISSUE TITLE
Show player perspective on minimap

### ISSUE THREAD

**Issue by Peragore** [Ahli/HomeStoryCup-mod#10]
Show colored frames on minimap where players are looking (ala ObserverPlusPlus). I believe this would finally bring HomestoryCup XX into line with all Obs++ functionality

**Comment by Ahli** [comment]
The players' camera positions are already visible on minimap. The frame hides when the player leaves or if it is not a human player.

Is there a difference that makes the ones in ObserverPlusPlus superior?

**Comment by Ahli** [comment]
I am closing this since the feature was already present and no feedback was given
